# help_text.py

HELP_TEXT = [
    "==================================== quickORTEP HELP ====================================",
    "",
    "NAVIGATION & VIEWING",
    "  Rotation:            h/l => Y axis       j/k => X axis       u/o => Z axis",
    "  Mouse Rotation:      Left drag => X/Y    Middle drag => Z    ",
    "  Panning:             H/L => X axis       J/K => Y axis       Right drag => pan",
    "  Zooming:             n/m => zoom in/out  Mouse wheel => zoom",
    "  View Operations:     F => fit molecule   r => reset view     Shift+Dbl-Click => reset",
    "",
    "SELECTION & BOND EDITING",
    "  Selection:           Left click => select      Shift+click => multi-select",
    "  Bond Types:          b => cycle bond types     B => toggle bond on/off",
    "  Bond Management:     P => toggle bond propagation across frames",
    "                       c => clear all bond edits",
    "  Visualization:       p => toggle energy/bond length plot",
    "",
    "DISPLAY OPTIONS",
    "  Atom Display:        d => toggle hydrogens     3 => toggle 3D effects",
    "  References:          g => toggle grid          a => toggle axes",
    "  Fog Effects:         f => cycle fog modes      ( / ) => adjust fog density",
    "",
    "TRAJECTORY & NORMAL MODES",
    "  Frame Navigation:    [ / ] => prev/next frame  { / } => first/last frame",
    "                       = / - => highest/lowest energy frame",
    "  Orientation:         t => std. orientation     T => std. orient. all frames",
    "  Normal Modes:        v => toggle vectors       , / . => prev/next mode",
    "                       < / > => scale mode vectors",
    "",
    "EXPORT & FILE",
    "  Export:              s => export SVG           x => export XYZ",
    "                       w => export graph data",
    "  File Operations:     R => reload current file",
    "",
    "GENERAL",
    "  Help & Exit:         ? => toggle this help     q/Esc => quit",
    "",
    "=========================================================================================",
]
